### ISSUE TITLE
meteor paths hardcoded

### ISSUE THREAD

**Issue by wh0** [luckychain/node-secureworker#1]
- where the enclave signing key is
- where the enclave DLL is

the API for this package has no way of passing this information in

**Comment by mitar** [comment]
Removed.

**Comment by mitar** [comment]
Not sure what happens if the same `.so` file is provided for two scripts. Is enclave established only once, or once for each file. It seems we call this every time we create a new instance of secure worker:

```
sgx_create_enclave(file_name, SGX_DEBUG_FLAG, &launch_token, &launch_token_updated, &enclave_id, NULL)
```
