### ISSUE TITLE
Additional packages required for bundling imports with browserify

### ISSUE THREAD

**Issue by panpan2** [luckychain/node-secureworker#14]
I am not sure if this is something worth mentioning or whether it doesn't have to do with the project but I in the README it's mentioned that one can bundle imports in a single file with browserify using:

`$ browserify --insert-global-vars __filename,__dirname --no-commondir -t [ babelify --presets [ es2015 ] ] enclave-source.js > enclave-bundle.js`

The above also requires babelify, babel-core and babel-preset-es2015 packages to work.

**Comment by mitar** [comment]
True. Maybe make a PR mentioning this next to that command?
